# Generated by Django 3.1.5 on 2021-01-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210122_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда', 'verbose_name_plural': 'Звезды'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.star', verbose_name='Рeйтинг'),
        ),
    ]
